Traceback (most recent call last):
  File "/Users/tadeatobatele/Documents/UniStuff/CS351 Project/code/PoSBlockchain/code_node2/Blockchain/Backend/core/network/syncManager.py", line 216, in handleConnection
    self.blockchain.addBlock(blockHeight, prevBlockHash, selected_validator)
  File "<string>", line 2, in addBlock
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/managers.py", line 836, in _callmethod
    raise convert_to_error(kind, result)
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/tadeatobatele/Documents/UniStuff/CS351 Project/code/PoSBlockchain/code_node2/Blockchain/Backend/core/network/syncManager.py", line 216, in handleConnection
    self.blockchain.addBlock(blockHeight, prevBlockHash, selected_validator)
  File "<string>", line 2, in addBlock
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/managers.py", line 836, in _callmethod
    raise convert_to_error(kind, result)
TypeError: list indices must be integers or slices, not str
Process Process-4:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tadeatobatele/Documents/UniStuff/CS351 Project/code/PoSBlockchain/code_node2/Blockchain/Backend/core/network/syncManager.py", line 48, in spinUpServer
    self.conn, self.addr = self.server.acceptConnection()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tadeatobatele/Documents/UniStuff/CS351 Project/code/PoSBlockchain/code_node2/Blockchain/Backend/core/network/connection.py", line 31, in acceptConnection
    self.conn, self.addr = self.server.accept()
                           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py", line 295, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
KeyboardInterrupt
Exception ignored in: <function BaseDB.__del__ at 0x105f26020>
Traceback (most recent call last):
  File "/Users/tadeatobatele/Documents/UniStuff/CS351 Project/code/PoSBlockchain/code_node2/Blockchain/Backend/core/database/db.py", line 129, in __del__
    self.conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6121009152 and this is thread id 8132452608.
Exception ignored in: <function BaseDB.__del__ at 0x105f26020>
Traceback (most recent call last):
  File "/Users/tadeatobatele/Documents/UniStuff/CS351 Project/code/PoSBlockchain/code_node2/Blockchain/Backend/core/database/db.py", line 129, in __del__
    self.conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6121009152 and this is thread id 8132452608.
Exception ignored in: <function BaseDB.__del__ at 0x105ba6020>
Traceback (most recent call last):
  File "/Users/tadeatobatele/Documents/UniStuff/CS351 Project/code/PoSBlockchain/code_node2/Blockchain/Backend/core/database/db.py", line 129, in __del__
    self.conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6161674240 and this is thread id 8132452608.
Exception ignored in: <function BaseDB.__del__ at 0x105ba6020>
Traceback (most recent call last):
  File "/Users/tadeatobatele/Documents/UniStuff/CS351 Project/code/PoSBlockchain/code_node2/Blockchain/Backend/core/database/db.py", line 129, in __del__
    self.conn.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 6144847872 and this is thread id 8132452608.
