2025-04-28 04:18:17,918 INFO: [PID 298194] start_node.py script started. Logging configured.
2025-04-28 04:18:17,919 INFO: [PID 298194] symlinked /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/node_0/data/data â†’ /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/node_0/data
2025-04-28 04:18:18,332 INFO: [PID 298220] Blockchain object __init__ called.
2025-04-28 04:18:18,353 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5900
2025-04-28 04:18:18,353 INFO: [33mPress CTRL+C to quit[0m
2025-04-28 04:18:18,427 INFO: [PID 298220] Ensured table exists in data/account.db
2025-04-28 04:18:18,427 INFO: [PID 298220] [PID 298220] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:18:18,432 INFO: [PID 298220] [PID 298220] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:18:18,458 INFO: [PID 298220] Ensured table exists in data/data/blockchain.db
2025-04-28 04:18:18,458 INFO: [PID 298220] Blockchain __init__: Test BlockchainDB connection successful.
2025-04-28 04:18:18,465 INFO: [PID 298220] Entering setup_node()
2025-04-28 04:18:18,465 INFO: [PID 298220] [PID 298220] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:18:18,473 INFO: [PID 298220] [PID 298220] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:18:18,484 INFO: [PID 298220] Ensured table exists in data/data/blockchain.db
2025-04-28 04:18:18,491 INFO: [PID 298220] [Node Setup] No existing blockchain found. Waiting...
2025-04-28 04:18:18,613 INFO: 127.0.0.1 - - [28/Apr/2025 04:18:18] "GET / HTTP/1.1" 200 -
2025-04-28 04:18:21,881 INFO: 127.0.0.1 - - [28/Apr/2025 04:18:21] "GET / HTTP/1.1" 200 -
2025-04-28 04:18:22,759 INFO: [PID 298239] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:18:22,762 INFO: [PID 298239] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:18:22,773 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:18:22,773 INFO: [PID 298239] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:18:22,774 INFO: [PID 298239] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:18:22,781 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:18:23,041 INFO: Ensured table exists in data/account.db
2025-04-28 04:18:23,090 INFO: Ensured table exists in data/account.db
2025-04-28 04:18:23,102 INFO: Ensured table exists in data/account.db
2025-04-28 04:18:23,130 INFO: Block written successfully.
2025-04-28 04:18:25,118 INFO: Ensured table exists in data/account.db
2025-04-28 04:18:25,469 INFO: [PID 298239] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:18:25,470 INFO: [PID 298239] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:18:25,474 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:18:25,479 INFO: [PID 298239] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:18:25,481 INFO: [PID 298239] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:18:25,483 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:18:25,704 INFO: Block written successfully.
2025-04-28 04:19:23,069 INFO: Ensured table exists in data/account.db
2025-04-28 04:19:23,075 INFO: Ensured table exists in data/account.db
2025-04-28 04:19:23,078 INFO: Ensured table exists in data/account.db
2025-04-28 04:19:23,080 INFO: [PID 298239] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:19:23,082 INFO: [PID 298239] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:19:23,084 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 04:19:25,141 INFO: [PID 298220] Ensured table exists in data/node.db
2025-04-28 04:19:25,516 INFO: [PID 298220] Ensured table exists in data/node.db
2025-04-28 04:19:25,520 INFO: [PID 298220] [PID 298220] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:19:25,526 INFO: [PID 298220] [PID 298220] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:19:25,528 INFO: [PID 298220] Ensured table exists in data/data/blockchain.db
2025-04-28 04:19:25,538 INFO: [PID 298220] Block written successfully.
2025-04-28 04:19:30,545 INFO: [PID 298220] [PID 298220] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:19:30,545 INFO: [PID 298220] [PID 298220] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:19:30,550 INFO: [PID 298220] Ensured table exists in data/data/blockchain.db
2025-04-28 04:19:30,553 INFO: [PID 298220] [PID 298220] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 04:19:30,553 INFO: [PID 298220] [PID 298220] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 04:19:30,557 INFO: [PID 298220] Ensured table exists in data/data/blockchain.db
