2025-04-28 14:48:39,288 INFO: [PID 310896] start_node.py script started. Logging configured.
2025-04-28 14:48:39,288 INFO: [PID 310896] symlinked /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/node_0/data/data â†’ /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/node_0/data
2025-04-28 14:48:39,670 INFO: [PID 310915] Blockchain object __init__ called.
2025-04-28 14:48:39,702 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5900
2025-04-28 14:48:39,703 INFO: [33mPress CTRL+C to quit[0m
2025-04-28 14:48:39,712 INFO: [PID 310915] Ensured table exists in data/account.db
2025-04-28 14:48:39,712 INFO: [PID 310915] Blockchain initialized for port 9000. Lock object received: <class 'multiprocessing.managers.AcquirerProxy'>
2025-04-28 14:48:39,718 INFO: [PID 310915] Entering setup_node()
2025-04-28 14:48:39,719 INFO: [PID 310915] [PID 310915] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 14:48:39,719 INFO: [PID 310915] [PID 310915] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 14:48:39,729 INFO: [PID 310915] Ensured table exists in data/data/blockchain.db
2025-04-28 14:48:39,731 INFO: [PID 310915] [Node Setup] No existing blockchain found. Waiting...
2025-04-28 14:48:41,735 INFO: [Startup] Node 0 initiating sync with peers...
2025-04-28 14:48:41,762 INFO: [PID 310915] Ensured table exists in data/node.db
2025-04-28 14:48:41,763 INFO: [PID 310915] [Downloader] Starting download from 8000 :9001...
2025-04-28 14:48:41,763 INFO: [PID 310915] [PID 310915] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 14:48:41,764 INFO: [PID 310915] [PID 310915] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 14:48:41,766 INFO: [PID 310915] Ensured table exists in data/data/blockchain.db
2025-04-28 14:48:41,772 INFO: [PID 310915] [Downloader] No local blocks found. Requesting from Genesis.
2025-04-28 14:48:41,773 WARNING: [PID 310915] Connection refused by 8000:9001.
2025-04-28 14:48:41,775 INFO: [Startup] Node 0 initial sync process finished.
2025-04-28 14:48:41,943 INFO: 127.0.0.1 - - [28/Apr/2025 14:48:41] "GET / HTTP/1.1" 200 -
2025-04-28 14:48:43,225 INFO: 127.0.0.1 - - [28/Apr/2025 14:48:43] "GET / HTTP/1.1" 200 -
2025-04-28 14:48:43,853 INFO: Ensured table exists in data/node.db
2025-04-28 14:48:44,238 INFO: Ensured table exists in data/account.db
2025-04-28 14:48:44,243 INFO: Ensured table exists in data/account.db
2025-04-28 14:48:44,245 INFO: Ensured table exists in data/account.db
Exception ignored in: <function BaseDB.__del__ at 0x7f12a813ae50>
Traceback (most recent call last):
  File "/dcs/project/algoblock/MainCode/PoSBlockchain/code_node2/Blockchain/Backend/core/database/db.py", line 129, in __del__
    self.conn.close()
