2025-05-02 06:02:16,991 INFO: [PID 766158] start_node.py script started. Logging configured.
2025-05-02 06:02:17,245 INFO: [PID 766158] Blockchain object __init__ called.
2025-05-02 06:02:17,274 INFO: [PID 766158] Blockchain initialized for port 9003. Lock object received: <class '_thread.lock'>
2025-05-02 06:02:17,280 INFO: [PID 766158] [PID 766158] BlockchainDB attempting to connect to: /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/validator_node/data/blockchain.db
2025-05-02 06:02:17,280 INFO: [PID 766158] [PID 766158] BlockchainDB connected successfully to: /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/validator_node/data/blockchain.db
2025-05-02 06:02:17,286 INFO: [PID 766158] Available validators (excluding 1CJL7mvokNjrs2D48jM3EEHoRhQiWCbxCh): ['14yikjhubj1sepvqsvzpRv4H6LhMN43XGD', '1DPPqS7kQNQMcn28du4sYJe8YKLUH8Jrig', '1Lu9SwPPo7DJYrMVrZnkDXVw5y4aEeF1kz']
2025-05-02 06:02:17,286 INFO: [PID 766158] Selected validator 14yikjhubj1sepvqsvzpRv4H6LhMN43XGD based on weighted random (stake: 10000000000)
2025-05-02 06:02:17,286 INFO: [PID 766158] [ValidatorSelector] Selected Validator: 14yikjhubj1sepvqsvzpRv4H6LhMN43XGD with stake 10000000000
2025-05-02 06:02:17,286 INFO: [PID 766158] Node connect: Connecting to ('127.0.0.1', 9000)...
2025-05-02 06:02:17,286 ERROR: [PID 766158] Node connect: Failed to connect to ('127.0.0.1', 9000): [Errno 111] Connection refused
2025-05-02 06:02:17,286 INFO: [PID 766158] Node connect: Connecting to ('127.0.0.1', 9001)...
2025-05-02 06:02:17,286 ERROR: [PID 766158] Node connect: Failed to connect to ('127.0.0.1', 9001): [Errno 111] Connection refused
2025-05-02 06:02:17,286 INFO: [PID 766158] Node connect: Connecting to ('127.0.0.1', 9002)...
2025-05-02 06:02:17,286 ERROR: [PID 766158] Node connect: Failed to connect to ('127.0.0.1', 9002): [Errno 111] Connection refused
