2025-04-28 14:48:41,313 INFO: [PID 310973] start_node.py script started. Logging configured.
2025-04-28 14:48:41,314 INFO: [PID 310973] symlinked /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/node_1/data/data â†’ /dcs/project/algoblock/MainCode/PoSBlockchain/network_data/node_1/data
2025-04-28 14:48:41,705 INFO: [PID 310992] Blockchain object __init__ called.
2025-04-28 14:48:41,732 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5901
2025-04-28 14:48:41,733 INFO: [33mPress CTRL+C to quit[0m
2025-04-28 14:48:41,747 INFO: [PID 310992] Ensured table exists in data/account.db
2025-04-28 14:48:41,747 INFO: [PID 310992] Blockchain initialized for port 9001. Lock object received: <class 'multiprocessing.managers.AcquirerProxy'>
2025-04-28 14:48:41,754 INFO: [PID 310992] Entering setup_node()
2025-04-28 14:48:41,755 INFO: [PID 310992] [PID 310992] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 14:48:41,756 INFO: [PID 310992] [PID 310992] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 14:48:41,766 INFO: [PID 310992] Ensured table exists in data/data/blockchain.db
2025-04-28 14:48:41,768 INFO: [PID 310992] [Node Setup] No existing blockchain found. Waiting...
2025-04-28 14:48:43,244 INFO: 127.0.0.1 - - [28/Apr/2025 14:48:43] "GET / HTTP/1.1" 200 -
2025-04-28 14:48:43,772 INFO: [Startup] Node 1 initiating sync with peers...
2025-04-28 14:48:43,796 INFO: [PID 310992] Ensured table exists in data/node.db
2025-04-28 14:48:43,797 INFO: [PID 310992] [Downloader] Starting download from 8001 :9000...
2025-04-28 14:48:43,798 INFO: [PID 310992] [PID 310992] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 14:48:43,799 INFO: [PID 310992] [PID 310992] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 14:48:43,803 INFO: [PID 310992] Ensured table exists in data/data/blockchain.db
2025-04-28 14:48:43,810 INFO: [PID 310992] [Downloader] No local blocks found. Requesting from Genesis.
2025-04-28 14:48:43,810 INFO: [PID 310992] [Downloader] Sent requestBlock to 8001:9000
2025-04-28 14:48:44,230 ERROR: [PID 310992] Error during download from 8001:9000: Connection closed before magic bytes received
Traceback (most recent call last):
  File "/dcs/project/algoblock/MainCode/PoSBlockchain/code_node2/Blockchain/Backend/core/network/syncManager.py", line 917, in startDownload
    envelope = connector.read()
  File "/dcs/project/algoblock/MainCode/PoSBlockchain/code_node2/Blockchain/Backend/core/network/connection.py", line 43, in read
    envelope = NetworkEnvelope.parse(self.stream)
  File "/dcs/project/algoblock/MainCode/PoSBlockchain/code_node2/Blockchain/Backend/core/network/network.py", line 19, in parse
    raise RuntimeError("Connection closed before magic bytes received")
RuntimeError: Connection closed before magic bytes received
2025-04-28 14:48:44,237 INFO: [Startup] Node 1 initial sync process finished.
2025-04-28 14:48:44,261 INFO: Ensured table exists in data/account.db
2025-04-28 14:48:44,270 INFO: Ensured table exists in data/account.db
2025-04-28 14:48:44,272 INFO: Ensured table exists in data/account.db
2025-04-28 14:48:44,276 INFO: [PID 311015] BlockchainDB.connect attempting: sqlite3.connect('data/data/blockchain.db')
2025-04-28 14:48:44,277 INFO: [PID 311015] BlockchainDB.connect successful for: 'data/data/blockchain.db'
2025-04-28 14:48:44,281 INFO: Ensured table exists in data/data/blockchain.db
2025-04-28 14:48:44,362 INFO: 127.0.0.1 - - [28/Apr/2025 14:48:44] "GET / HTTP/1.1" 200 -
